spring:
  application:
    name: customer-service
  datasource:
    name: techCutomerDb
    url:  jdbc:mysql://localhost:3306/techCutomerDb?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
