global:
    message: Welcome to customer service Prod environment
server:
    port: 8082
message: Hello from customer service Prod!
spring:  
  datasource:
    name: techCutomerDb_Prod
    url:  jdbc:mysql://localhost:3306/techCutomerDb_Prod?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true