global:
    message: Welcome to order service Dev environment
server:
    port: 8084
message: Hello from order service Dev!
spring:  
  datasource:
    name: techOrderDb_Master
    url:  jdbc:h2:mem:techOrderDb_Master
    username: root
    #driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true