spring:
  application:
    name: tech-order-service
  datasource:
    name: techOrderDb_Master
    url:  jdbc:h2:mem:techOrderDb_Master
    username: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
